csiro-coasts/emsarray

continuous-integration/requirements.txt
tox.ini

* Bumps pytest version
* ensures the correct version of python is used (basepython is tricksy)
* Collapses flake8, isort, and mypy to one tox environment

More tox shenanigans

---

continuous-integration/environment.yaml
continuous-integration/requirements.txt
docs/installing.rst
setup.cfg
src/emsarray/compat/shapely.py
src/emsarray/formats/_base.py
src/emsarray/formats/arakawa_c.py
src/emsarray/formats/grid.py
src/emsarray/formats/ugrid.py
tests/formats/test_base.py
tox.ini

shapely previously depended on the proj library being installed, but this is no longer true. I think it is bundled somewhere in the dependency chain? Anyway, no point in installing it any more!

Remove explicit proj dependency

---

src/emsarray/formats/_base.py
src/emsarray/formats/arakawa_c.py
src/emsarray/formats/grid.py
src/emsarray/formats/ugrid.py
src/emsarray/masking.py
tests/formats/test_base.py
tests/formats/test_cfgrid1d.py
tests/formats/test_shoc_standard.py
tests/formats/test_ugrid.py

Adds a `buffer: int = 0` argument to `make_clip_mask()` that allows users to opt-in to a buffer around the clip geometry.
Closes #12

Make clip buffer configurable

---

continuous-integration/docs.yaml

I had forgotten that there was a separate conda environment for the docs, and that it pointed to the requirements file that had moved.

Fix readthedocs environment

---

docs/releases.rst
src/emsarray/formats/_base.py
src/emsarray/formats/arakawa_c.py
src/emsarray/formats/grid.py
src/emsarray/formats/shoc.py
src/emsarray/formats/ugrid.py
src/emsarray/operations.py
src/emsarray/utils.py

This is the type exposed by xarray. NetCDF4 enforces string names, but other data types might allow different variable name types.
This actually cleans up the code by removing a whole bunch of casting.

Ustrse `Hashable` instead of `str` for variable and dimension names

---

docs/api/exceptions.rst
docs/api/index.rst
docs/releases.rst
docs/roles.py
src/emsarray/exceptions.py
src/emsarray/formats/ugrid.py
tests/formats/test_ugrid.py

Fix error when UGRID `start_index` is the string `"0"` or `"1"`. The conventions imply this should be an integer type, however real datasets use a string value here so a tolerant implementation is useful.

Fix issue when UGRID `start_index` is the string "0" or "1"

---

docs/api/operations/index.rst
docs/api/operations/point_extraction.rst
docs/cli.rst
docs/releases.rst
src/emsarray/cli/__init__.py
src/emsarray/cli/extract_points.py
src/emsarray/formats/_base.py
src/emsarray/formats/arakawa_c.py
src/emsarray/formats/grid.py
src/emsarray/formats/ugrid.py
src/emsarray/operations/point_extraction.py
tests/formats/test_base.py

* Adds a new `Format.drop_geometry()` method
* Adds a new `emsarray.operations.point_extraction` module that can extract data at points given in a Pandas DataFrame.
* Adds a new `emsarray extract-points` command line entry point
Closes #13

Point extraction

---

docs/releases.rst
setup.cfg

Messed up the 'Release notes' URL in setup.cfg, and the only way to update the PyPI metadata is to publish another version!

Release 0.3.1

---

docs/api/formats/ugrid.rst
src/emsarray/accessors.py
src/emsarray/formats/_base.py
src/emsarray/formats/_helpers.py
src/emsarray/state.py
tests/formats/test_ugrid.py
tests/test_binding.py

Adds a mechanism to bypass automatic format detection.
xarray accessors like `dataset.ems` are read only and cached. They can not be manually set. Simply doing `dataset.ems = SomeFormat(dataset)` does not work, and once set a format can not be swapped out. As such, an alternate mechanism to bind formats to datasets was required. The `emsarray.state.State` class represents this. This has attributes that _are_ modifiable. A new Format instance can be constructed and bound to a dataset - this will set the `state.format` attribute. When `dataset.ems` is then accessed, the accessor will first check to see if a custom format has already been bound. If one has been, this will be used, else a new format will be constructed using the usual autodetection method.
This allows for greater flexibility …

Manual format binding

---

continuous-integration/requirements.txt
setup.cfg
src/emsarray/cli/utils.py
src/emsarray/conventions/_base.py
src/emsarray/conventions/arakawa_c.py
src/emsarray/conventions/grid.py
src/emsarray/conventions/ugrid.py
tests/cli/test_utils.py
tests/conventions/test_base.py

Shapely 2 exposes a [`shapely.polygons`](https://shapely.readthedocs.io/en/stable/reference/shapely.polygons.html#shapely.polygons) function which can create large numbers of polygons directly from numpy arrays. This gives a dramatic performance improvement, varying by dataset type. For UGRID I have seen the time taken to construct the polygons halve, for large CF grids the time has dropped from ~6 seconds to ~0.1 second.
This makes #40 irrelevant. This was found when investigating caching strategies. The slow down was always in constructing the polygons not in calculating vertices, and polygons still have to be constructed when loading them from the cache.

Faster polygon construction using Shapely 2.0.0

---

src/emsarray/cli/commands/export_geometry.py
src/emsarray/operations/geometry.py
src/emsarray/operations/triangulate.py
tests/conventions/test_ugrid.py
tests/operations/triangulate/test_triangulate_dataset.py

* When dumping geometry to GeoJSON, Features are made in an iterator and dumped as they are generated. This saves time and memory compared to precomputing all Features, then dumping the whole list of them.
* Triangulating datasets is slightly more efficient. Some Polygons were formed and then immediately thrown after fetching their coordinates. The coordinates are passed around directly instead.
* The time taken to generate polygons when exporting geometry is logged, for the sake of benchmarking.

Small efficiency improvements

---

.github/actions/build-python-package/action.yaml
.github/actions/environment/action.yaml
.github/workflows/ci.yaml
.github/workflows/release-branch.yaml
.github/workflows/release-tags.yaml

Three workflows for the different stages required:
* Regular CI job that runs the tests and lints the code for every pull request
* A prerelease CI job that runs additional checks for `release-*` branches
* A publish CI job that builds and publishes a new package from tagged commits

Split CI workflows

---

setup.cfg
src/emsarray/plot.py
tests/conventions/test_cfgrid1d.py
tests/conventions/test_ugrid.py

I noticed this because of some bad styles that were not being picked up. Some digging showed that some checks were disabled by default because they are not strictly mentioned in PEP8. I enabled all the checks by default, we can choose to disable specific ones if required in the future.

Enable all flake8 errors and warnings by default

---

docs/cli.rst
docs/releases/development.rst
src/emsarray/cli/commands/plot.py
src/emsarray/plot.py
tests/cli/commands/test_plot.py
tests/conftest.py
tests/conventions/test_base.py

Useful for quickly examining a dataset in an interactive environment. Making matplotlib patches is painfully slow, so this is not useful for large datasets with many cells.

Add `emsarray plot` subcommand

---

docs/releases/development.rst
src/emsarray/conventions/_base.py
src/emsarray/plot.py
tests/conventions/test_base.py
tests/test_plot.py

It is significantly faster! Doesn't seem to be any down sides. I had previously dismissed it as I didn't think it supported polygons with different numbers of vertices, but that was because I had read the docs incorrectly.
`Convention.make_patch_collection()` is now deprecated, and is an alias for `Convention.make_poly_collection()`. Unless a user is specifically expecting a PatchCollection everything should continue to work - the two classes take most of their functionality from the common underlying `Collection` class.

Use PolyCollection over PatchCollection in matplotlib plots

---

docs/releases/development.rst
src/emsarray/cli/commands/export_geometry.py
src/emsarray/cli/utils.py
src/emsarray/conventions/_base.py
src/emsarray/conventions/arakawa_c.py
src/emsarray/conventions/grid.py
src/emsarray/conventions/ugrid.py
src/emsarray/utils.py

`@timed_func` when used as a decorator will log the execution time of the wrapped function. Useful for decorating methods like `Convention.polygons` or others that take some time and are important to track.

Add `emsarray.utils.timed_func`, set up loggers for plugins

---

docs/releases/development.rst
src/emsarray/conventions/_base.py
src/emsarray/conventions/grid.py
src/emsarray/conventions/ugrid.py
src/emsarray/types.py
tests/conventions/test_base.py
tests/conventions/test_cfgrid1d.py
tests/conventions/test_cfgrid2d.py
tests/conventions/test_ugrid.py
tests/utils.py

Convention.geometry is a single Polygon that represents the dataset geometry, while Convention.bounds is the minimum bounds of the dataset. Both have default implementations, but specific conventions can override this implementation if there is a more efficient way of computing it.

Add Convention.geometry and Convention.bounds

---

.github/actions/environment/action.yaml
.github/workflows/ci.yaml
continuous-integration/requirements.txt
docs/releases/development.rst
setup.cfg
tests/masking/test_utils.py
tox.ini

The latest version tests are allowed to fail in CI. They act as a warning of future issues once we bump supported versions.
This also drops support for Python 3.8, following the lead of numpy and other prominent packages.

Update minimum versions, add tests against latest dependency versions

---

docs/releases/development.rst
src/emsarray/conventions/__init__.py
src/emsarray/conventions/_base.py
src/emsarray/conventions/arakawa_c.py
src/emsarray/conventions/grid.py
src/emsarray/conventions/ugrid.py
src/emsarray/operations/geometry.py
src/emsarray/plot.py
src/emsarray/utils.py
tests/conventions/test_base.py
tests/conventions/test_cfgrid1d.py
tests/conventions/test_cfgrid2d.py
tests/conventions/test_shoc_standard.py
tests/conventions/test_ugrid.py
tests/operations/test_geometry.py
tests/test_utils.py

Most conventions define grids on non-overlapping sets of dimensions. For example, Arakawa C datasets have four different grids, where each grid uses two dimensions, but no two grids share any dimensions. An index is a combination of a grid kind and a set of indices that match the grid dimensions. All current conventions follow this pattern.
A new DimensionConvention subclass has been added that encapsulates this. By formalising this relationship default implementations for `.ravel_index`, `.wind_index`, `.ravel`, `.selector_for_index`, and `.get_grid_kind` can be provided
As part of this, the antonyms 'ravel' and 'wind' replaced 'ravel' and 'unravel'. Numpy uses 'ravel' and 'unravel' to mean the inverse operation, but in English 'ravel' and 'unravel' mean the same thing. 'Wind' was chosen …

Dimension convention

---

docs/concepts/indexing.rst
docs/developing/grass.py
docs/releases/development.rst
src/emsarray/conventions/_base.py
src/emsarray/conventions/arakawa_c.py
src/emsarray/conventions/grid.py
src/emsarray/conventions/ugrid.py
tests/conventions/test_base.py

Convention.spatial_index was a compatibility shim for shapely.strtree.STRtree, which changed considerably between versions 1.8 and 2.0. Version 2.0 is considerably improved, and can be used directly now. This PR deprecates the shim. Users should instead use the strtree directly.

Add Convention.strtree, deprecate Convention.spatial_index

---

docs/concepts/indexing.rst
docs/releases/development.rst

Fix some ravel/wind docs I missed

---

docs/releases/development.rst
src/emsarray/conventions/_base.py
src/emsarray/operations/depth.py
tests/operations/depth/test_normalize_depth_variables.py

If `positive_down` or `deep_to_shallow` are none, those parts of the depth variable are not normalized. Users can choose which aspects of the depth variable to normalize.

Make `normalize_depth_variables()` parameters optional

---

docs/releases/development.rst
src/emsarray/plot.py

There are currently a number of problems with gridlines on plots in Jupyter notebooks. There are different solutions that depend on whether you want an interactive plot, a static plot in a notebook, or are saving the plot to a file. Unfortunately there is no single solution that works in all cases currently. Until a proper solution is found, users can disable gridlines and then re-enable them in the way that works for their current environment.
https://github.com/SciTools/cartopy/issues/2245
https://github.com/SciTools/cartopy/issues/2246
https://github.com/SciTools/cartopy/issues/2247

Make coasts and gridlines optional on plots

---

tests/conventions/test_cfgrid1d.py
tests/conventions/test_cfgrid2d.py
tests/conventions/test_shoc_standard.py
tests/conventions/test_ugrid.py
tests/masking/test_mask_dataset.py
tests/test_utils.py

xarray now explicitly complains if you're doing Bad Things, instead of silently trying to work with it. Explicit warnings are good! But now I have to not do those Bad Things.
This has the upside of removing one of the warnings the tests silenced, which can only be a good thing.

Fix some warnings raised in the tests with xarray 2023.09.0

---

continuous-integration/requirements.txt
docs/releases/development.rst
pyproject.toml
setup.cfg
src/emsarray/conventions/_registry.py
tests/conventions/test_registry.py

This was only required to support Python 3.8 and below, which was dropped recently. Some small shenanigans were required to support Python 3.9. Dask still depends on importib_metadata so it will still be installed regardless in most circumstances.

Drop dependency on importlib_metadata

---

docs/releases/development.rst
src/emsarray/conventions/shoc.py
tests/conventions/test_cfgrid2d.py
tests/conventions/test_shoc_standard.py

This can happen after selecting a single layer, for example.
Fixes #123

Support simple SHOC datasets with no depth coordinate

---

docs/examples/kgari-transect.py
docs/releases/development.rst

https://opus.nci.org.au/display/NDP/THREDDS+Upgrade

Update NCI thredds URL

---

docs/api/types.rst
docs/conf.py
docs/releases/development.rst
src/emsarray/conventions/_base.py
src/emsarray/operations/depth.py
src/emsarray/transect.py
src/emsarray/types.py
src/emsarray/utils.py
tests/conventions/test_base.py
tests/test_utils_data_array_getters.py

Two new functions `emsarray.utils.name_to_data_array` and `emsarray.utils.data_array_to_name` have been added to accomplish this. `Convention._get_data_array()` has been deprecaterd in favour of `name_to_data_array`.
WIP, still needs some tests for the new functions.

Expand more functions that accept DataArrayOrName

---

docs/releases/development.rst
src/emsarray/cli/commands/extract_points.py
src/emsarray/conventions/_base.py
src/emsarray/conventions/shoc.py
src/emsarray/operations/depth.py
src/emsarray/transect.py
tests/conventions/test_base.py
tests/conventions/test_cfgrid1d.py
tests/conventions/test_cfgrid2d.py
tests/conventions/test_shoc_standard.py
tests/conventions/test_ugrid.py
tests/operations/depth/test_ocean_floor.py

As per #140, there are far too many methods that deal with depth coordinates. Since #142 it is possible to use either a variable or its name interchangeably in most methods, making one of `Convention.depth_coordinate` or `Convention.get_depth_name()` et al superfluous. This PR drops `Convention.get_depth_name()` and similar methods in preference of using the coordinate variables directly.
Closes https://github.com/csiro-coasts/emsarray/issues/138, https://github.com/csiro-coasts/emsarray/issues/140

Consolidate depth coordinate methods

---

docs/developing/grass.py
docs/roles.py
scripts/min_deps_check.py
scripts/release.py
src/emsarray/cli/command.py
src/emsarray/cli/commands/export_geometry.py
src/emsarray/cli/commands/plot.py
src/emsarray/cli/utils.py
src/emsarray/compat/shapely.py
src/emsarray/conventions/_base.py
src/emsarray/conventions/_registry.py
src/emsarray/conventions/arakawa_c.py
src/emsarray/conventions/grid.py
src/emsarray/conventions/shoc.py
src/emsarray/conventions/ugrid.py
src/emsarray/formats.py
src/emsarray/nco.py
src/emsarray/operations/depth.py
src/emsarray/operations/geometry.py
src/emsarray/plot.py
src/emsarray/transect.py
src/emsarray/utils.py
tests/conventions/test_base.py
tests/conventions/test_registry.py
tests/datasets/make_examples.py
tests/operations/depth/test_normalize_depth_variables.py
tests/utils.py

The primary change is updating type hints to use PEP 604 features: `X | Y` over `Union[X, Y]` and `X | None` over `Optional[X]`.
Ref #109

Upgrade to Python 3.10 using pyupgrade

---

tests/test_plot.py

shapely.Point.coords.xy changed its return type to be consistent with all other geometry coords.xy return types, but we were relying on the previous behaviour.

Fix error in tests with shapely 2.0.5

---

docs/releases/development.rst
src/emsarray/conventions/grid.py
tests/conventions/test_cfgrid2d.py
tests/utils.py

Some `CFGrid2D` datasets contain 'river' geometry - single cell wide stretches surrounded by `nan`s. CFGrid2D datasets can contain cell bounds, but in instances where the dataset does not contain cell bounds the polygons generated by emsarray were invalid along river cells.
Example of a 'river' geometry with cell bounds. Red circles are the cell centres described by the longitude/latitude variables. Blue polygons are the cell geometry described by the cell bounds:
Without bounds, emsarray previously generated geometry that looked like. Red circles are the cell centres described by the longitude/latitude variables. Blue polygons are the polygons constructed by emsarray. The polygons extending along the river are invalid as they contain multiple overlapping points, and in total describe a …

Fix generated bounds for 'river' cells in CFGrid2D datasets

---

docs/releases/development.rst
src/emsarray/operations/triangulate.py

The ear clipping method is correct for all polygons, but slow. For convex polygons a fan triangulation is much quicker. Most polygons will be convex. For an example dataset this sped up triangulation on my machine from around 6 seconds to 1 second.

Generate a fan triangulation for convex polygons

---

docs/releases/development.rst
src/emsarray/conventions/_base.py
src/emsarray/conventions/arakawa_c.py
src/emsarray/conventions/grid.py
src/emsarray/conventions/ugrid.py
src/emsarray/exceptions.py
src/emsarray/operations/triangulate.py
tests/conventions/test_base.py

This came about after #154 which was generating invalid polygons which were not picked up. This PR introduces a post-processing step on the `Convention.polygons` property which checks the polygons to ensure they are valid polygons. Invalid polygons will spoil other operations so it is good to be certain.
This change effectively requires any implementing conventions to rename their `polygon` property to a `_make_polygons()` method. The base `Convention` class now includes a `polygon` property which calls this new method and post-processes the results. ~A new 'hotfix' concept is being trialled here which can adapt a Convention with a `polygon` property and without a `_make_polygons()` method to the new interface. This is novel but honestly there is only one plugin for emsarray so possibly …

Test polygons are valid after constructing them

---

.github/actions/environment/action.yaml

v2 started breaking because mamba was no longer being installed. Instead of debugging I'm upgrading to the latest release which includes the libmamba solver, making plain conda as fast as mamba.

Update conda-incubator/setup-miniconda action to v3

---

docs/api/operations/cache.rst
docs/api/operations/index.rst
docs/releases/development.rst
src/emsarray/conventions/_base.py
src/emsarray/operations/cache.py
tests/operations/test_cache.py

Added cache key operations that provide a hash key suitable for caching data derived from the geometry of a dataset.

Dataset Cache Keys

---

src/emsarray/conventions/grid.py
src/emsarray/conventions/ugrid.py
src/emsarray/operations/triangulate.py
tests/conventions/test_ugrid.py
tests/operations/triangulate/test_triangulate_dataset.py

Further to #151 this PR adds improvements to both polygon generation speeds and triangulation speeds. The improvements compared to 0.7.0 are huge with many datasets triangulated in under a second. For some conventions the slowest part became constructing the dataset polygons rather than the triangulation, so that has been improved as well.
The following triangulation speeds were observed on my laptop for various datasets and versions of emsarray. I only did one run per version so these numbers are not a thorough benchmark.
Dataset | Convention | Polygons | Triangles | 0.7.0 (s) | 0.8.0 (s) | #163 (s)
-- | -- | --: | --: | --: | --: | --:
gbr4 | ShocSimple | 92565 | 185130 | 18.3000 | 7.4340 | 0.5143
setas | UGrid | 10072 | 38496 | 5.9360 | 1.1820 | 0.3006
access_vt | CFGrid1D | 857960 | …

Triangulation speed

---

.github/actions/build-python-package/action.yaml
.github/actions/environment/action.yaml
.github/workflows/ci.yaml
.github/workflows/release-tags.yaml

Updating github actions to resolve deprecation failures.
Link: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Changes needed: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md

Updated upload and download github actions.

---

tests/masking/test_utils.py

xarray will in the future stop automatically decoding timedelta variables. It has added a FutureWarning about this. This warning was causing the latest dependency CI checks to fail.
This particular test is specifically about timedelta handling, so we want to opt in to decoding timedelta values.

Fix a FutureWarning from xarray around timedelta decoding

---

docs/conf.py

The Cartopy docs are now on readthedocs. We use intersphinx for building docs that link to other projects. As the docs have been moved and there is no redirect for the `objects.inv` file our docs build was breaking. Easily fixed by updating the URL for intersphinx to the new location.
See also: https://github.com/SciTools/cartopy/pull/2558

Fix Cartopy docs URL
